# Generated by Django 5.2.10 on 2026-02-09 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('history', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ECO', 'Eco-Tourism'), ('CULTURAL', 'Cultural Heritage')], max_length=20)),
                ('location_lat', models.FloatField(help_text='Latitude for Google Maps')),
                ('location_lng', models.FloatField(help_text='Longitude for Google Maps')),
                ('image', models.ImageField(upload_to='destinations/')),
                ('best_time_to_visit', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homestay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.TextField(help_text='e.g. WiFi, Local Food, Hot Water')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homestays', to='destinations.destination')),
            ],
        ),
        migrations.CreateModel(
            name='LocalGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('experience_years', models.IntegerField(default=0)),
                ('languages', models.CharField(help_text='e.g. Hindi, English, Tribal', max_length=200)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_verified', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='destinations.destination')),
            ],
        ),
    ]
