# Generated by Django 5.2.10 on 2026-02-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='best_time_to_visit',
            new_name='best_time',
        ),
        migrations.RenameField(
            model_name='localguide',
            old_name='phone',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='location_lng',
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='localguide',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='localguide',
            name='price_per_day',
        ),
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localguide',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Per Day', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homestay',
            name='amenities',
            field=models.TextField(help_text='WiFi, Local Food, etc.'),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='languages',
            field=models.CharField(help_text='e.g., Hindi, English, Nagpuri', max_length=200),
        ),
    ]
