# Generated by Django 5.2.10 on 2026-02-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_homestay_is_verified_chatconversation_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localguide',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
