# Generated by Django 5.2.10 on 2026-02-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_localguide_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='state',
            field=models.CharField(default='Jharkhand', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='visiting_time',
            field=models.CharField(blank=True, default='9:00 AM - 6:00 PM', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(default=23.3441),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(default=85.3096),
        ),
    ]
