# Generated by Django 5.2.10 on 2026-02-10 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_destination_state_destination_visiting_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localguide',
            name='contact',
        ),
        migrations.AddField(
            model_name='localguide',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='best_time',
            field=models.CharField(default='October to March', max_length=100),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='amenities',
            field=models.TextField(default='WiFi, Local Food, Parking'),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='title',
            field=models.CharField(default='My India Trip', max_length=200),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_itineraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Per Day Fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='languages',
            field=models.CharField(default='Hindi, English', max_length=200),
        ),
    ]
