# Generated by Django 5.2.10 on 2026-02-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_remove_localguide_contact_localguide_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homestay',
            name='contact',
            field=models.CharField(default='Not Provided', max_length=20),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='localguide',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
