# Generated by Django 5.2.10 on 2026-04-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_alter_homestay_contact_alter_localguide_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='localguide',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
