from django.db import models
from django.conf import settings
from destinations.models import Destination

class TripPlan(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='trip_plans')
    title = models.CharField(max_length=200, default="My Jharkhand Trip")
    days = models.IntegerField()
    interests = models.CharField(max_length=50) # Eco or Cultural
    itinerary_data = models.JSONField() # Stores the day-wise plan generated by AI
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.email} - {self.title} ({self.days} Days)"